media:
  input: assets/images
  output: /assets/images

content:
  - name: portfolio
    label: "Annika's Portfolio"
    type: file
    path: gallery.json
    fields:
      - name: photos
        label: Photos
        type: object
        list: true
        fields:
          - name: image
            label: Image
            type: image
          - name: caption
            label: Description
            type: string
          - name: category
            label: Category
            type: select
            options:
              values:
                - Color
                - Cut
                - Styling
